####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret time_zone
  whitelist_external_dirs:
    - /config               # for filesize sensor
    - /tmp                  # for camera snapshots
    - /dev                  # for camera snapshots
    - /share

####################################################
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include_dir_merge_list automation/
cloud: !include cloud.yaml
climate: !include climate.yaml
frontend: !include frontend.yaml
ios: !include ios.yaml
media_player: !include media_player.yaml
notify: !include notification.yaml
packages: !include_dir_named packages # Include Packages
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

#https://home-assistant.io/components/config/
config:

#https://www.home-assistant.io/integrations/discovery/
discovery:
  ignore:
  - yeelight
  - plex_mediaserver
  - google_cast

#https://www.home-assistant.io/hassio/
hassio:

#https://home-assistant.io/components/history/
history:

#https://home-assistant.io/components/http/
http:
  base_url: !secret url

#https://home-assistant.io/components/logger/
logger:
  default: error

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml

#https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

#https://github.com/smartHomeHub/SmartIR
smartir:

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/components/system_health/
system_health:

#https://www.home-assistant.io/integrations/google_translate/
tts:
  - platform: google_translate
    language: 'th'

####################################################
#                    GROUP                         #
####################################################

#https://www.home-assistant.io/components/group/
group:


####################################################
#                DEVICE TRACKER                    #
####################################################

#https://www.home-assistant.io/integrations/device_tracker/
device_tracker:
  - platform: nmap_tracker
    home_interval: 3
    hosts: 
      - !secret ball_device
      - !secret peamai_device

device_tracker:
  - platform: bluetooth_tracker
####################################################
#                   PERSON                         #
####################################################

#https://www.home-assistant.io/components/person/
person:
  - name: Ball
    id: ball
    device_trackers:
      - device_tracker.ball_phone  #WiFi
      - device_tracker.ball_phone_2 #GPS
  - name: Peamai
    id: peamai
    device_trackers:
      - device_tracker.peamai_phone #WiFi
      - device_tracker.peamai_phone_2 #GPS

####################################################
#                    ASUS WRT                      #
####################################################

#https://www.home-assistant.io/integrations/asuswrt/
asuswrt:
  host: !secret router_device
  username: !secret ball_username
  port: !secret asus_port
  ssh_key: /config/id_rsa
  sensors:
    - upload
    - download
    - upload_speed
    - download_speed

####################################################
#                      IFTTT                       #
####################################################

#https://www.home-assistant.io/integrations/ifttt/
ifttt:
  key: !secret ifttt_key